/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IncomeCategory {
  id: number;
  parentId: number | null;
  name: string;
  createdAt: string;
  updatedAt: string;
}
