/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Currency = "PLN" | "GBP" | "USD" | "EUR";

export interface Transfer {
  id: string;
  amount: number;
  currency: Currency;
  sourceAccount: string;
  recipientAccount: string;
  recipient: string;
  title: string;
  scheduledAt: string;
  executeAt: string;
}
