/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface User {
  id: number;
  departmentId: number;
  firstName: string;
  lastName: string;
  title: string;
  age: number;
  email: string;
  salary: number;
  addresses: Address[];
  bio: string;
  hiredAt: string;
  expiresAt: string;
  retiresAt?: string;
}
export interface Address {
  street: string;
  city: string;
  country: string;
}
